from src.Searcher import Searcher

if __name__ == "__main__":
    searcher = Searcher("english.xlsx")
    searcher.tokenize()
    print('>>> tokenizing: ________________________________________________________________')
    print(searcher.vocab)
    searcher.remove_stop_words()
    print('>>> remove stop words: _________________________________________________________')
    print(searcher.vocab)
    searcher.stem_words()
    print('>>> stem words: _________________________________________________________________')
    print(searcher.vocab)
    searcher.vectorize()
    print('>>> vectorize: __________________________________________________________________')
    print(searcher.vocab)
    searcher.calc_term_doc()
    print('>>> term document: ______________________________________________________________')
    searcher.tf_idf_score()
    print('>>> tf_idf: _____________________________________________________________________')
    print(searcher.term_doc_matrix)
    searcher.term_doc_matrix.to_csv('../out/term_doc_matrix.csv')
    print(searcher.search_query('25 batman tom'))
